@baseUrl = http://localhost:5000
@urlPath = api/v1

### add reactions to a Post with Post ID.
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "6510896118879910c71e7cb9",
  "postId": "6513146ae3bef33b131eb6f9",
  "type": "love",
  "previousReaction": "",
  "postReactions": {"like": 0,"love": 1,"happy": 0,"sad": 0,"wow": 0,"angry": 0},
  "profilePicture": "https://res.cloudinary.com/dyamr9ym3/image/upload/v1659189696/62e539c0d8b514f6e42e3b5b"
}

### remove reaction with post Id,previous reaction, post reactions
DELETE {{baseUrl}}/{{urlPath}}/post/reaction/65104f17799af352f7760acf/happy/{"like": 0,"love": 0,"happy": 0,"sad": 0,"wow": 0,"angry": 0}
Content-Type: application/json
Accept: application/json
withCredentials: true

### get all the reactions of a post with post id.
GET {{baseUrl}}/{{urlPath}}/post/reactions/65104f17799af352f7760acf
Content-Type: application/json
Accept: application/json
withCredentials: true

### get a reaction of one user in a post with post id.
GET {{baseUrl}}/{{urlPath}}/post/single/reaction/username/sharath/6513146ae3bef33b131eb6f9
Content-Type: application/json
Accept: application/json
withCredentials: true

### get all reactions of a user.
GET {{baseUrl}}/{{urlPath}}/post/reactions/username/sharath
Content-Type: application/json
Accept: application/json
withCredentials: true
